version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:5000
    volumes:
      - ./greenlight.nginx:/etc/nginx/conf.d/default.conf
  app:
    entrypoint: [bin/start]
    image: eu.gcr.io/theta-elearning-demo/theta-greenlight:v2 
    container_name: theta-greenlight-v2
    env_file: .env-development
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
    depends_on:
      - nginx
# When using sqlite3 as the database
#      - ./db/development:/usr/src/app/db/development
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/development:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
